name: Block Invalid Release Branches

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  block-invalid-release-pr:
    uses: salva133/My-Workflows/.github/workflows/block-invalid-release-branches.yml@796f3f07e142746d2635e9defc1e850c44221fa2
    with:
      head_ref: ${{ github.head_ref }}
