name: Block Invalid Release Branches

on:
  pull_request:
    branches:
      - master

jobs:
  block-invalid-release-pr:
    uses: salva133/My-Workflows/.github/workflows/block-invalid-release-branches.yml@6512f6250a807e134b648f32e7231ae71a44c544
    with:
      head_ref: ${{ github.head_ref }}
