name: Bump Build Number

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  bump-build-number:
    if: github.event.pull_request.merged == true
    uses: salva133/My-Workflows/.github/workflows/bump-build-number.yml@f3bafa6488ba6ea41089f2beb0ced938b16e4219
    with:
      pr_number: ${{ github.event.pull_request.number }}
