name: Create steam_desc from README

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  create-steam_desc-from-README:
    uses: salva133/My-Workflows/.github/workflows/create-steam_desc-from-README.yml@latest
