name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

  workflow_dispatch:

jobs:
  create-release:
    if: github.event.pull_request.merged == true
    uses: salva133/My-Workflows/.github/workflows/create-release.yml@c1243e8785cbe3442c689ce1131a4a016b880961
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_body: ${{ github.event.pull_request.body }}
