name: Create steam_desc from README

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

  workflow_dispatch:

jobs:
  create-steam_desc-from-README:
    uses: salva133/My-Workflows/.github/workflows/create-steam_desc-from-README.yml@d13105a79ae640613704286529470ca59be68a13
