name: Remove Trailing Whitespace

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - '**/*.txt'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  remove-trailing-whitespaces:
    if: github.event.pull_request.merged == true
    uses: salva133/My-Workflows/.github/workflows/remove_trailing_whitespaces.yml@latest
    with:
      script-path: '.github/scripts/remove_trailing_whitespaces.py'
      commit-message: 'chore: remove trailing whitespace'
      reusable-repo-ref: 'master'
