name: Trim Trailing Whitespace

on:
  push:
    branches:
      - master

jobs:
  trim-whitespace:
    if: github.event.pull_request.merged == true
    uses: salva133/My-Workflows/.github/workflows/trim-trailing-whitespace.yml@6512f6250a807e134b648f32e7231ae71a44c544
