name: Trim Trailing Whitespace

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  trim-whitespace:
    if: github.event.pull_request.merged == true
    uses: salva133/My-Workflows/.github/workflows/trim-trailing-whitespace.yml@f3bafa6488ba6ea41089f2beb0ced938b16e4219